### This notebook is the compatible version that works with ALX Interactive Visualizations module exercises. The learner is expected to learn about how to create advanced custom visualizations and interactive visualizations in a Jupyter notebook

In [15]:
!pip install scipy
!pip install ipywidgets
!pip install chart-studio
!pip install pyarrow
!pip install cufflinks

Requirement already satisfied: scipy in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (1.7.3)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from scipy) (1.21.6)
Requirement already satisfied: ipywidgets in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (8.1.8)
Requirement already satisfied: ipython>=6.1.0 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipywidgets) (7.31.1)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: comm>=0.1.3 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipywidgets) (0.1.4)
Requirement already satisfied: widgetsnbextension~=4.0.14 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: traitlets>=4.3.1 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipywidgets) (5.7.1)
Requirement already satisfied: jedi>=0.16 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.18.1)
Requirement already satisfied: backcall in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.0)
Requirement already satisfied: colorama in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: pygments in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.11.2)
Requirement already satisfied: pickleshare in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.7.5)
Requirement already satisfied: setuptools>=18.5 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=6.1.0->ipywidgets) (65.6.3)
Requirement already satisfied: matplotlib-inline in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.6)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.36)
Requirement already satisfied: decorator in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: wcwidth in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=6.1.0->ipywidgets) (0.2.5)
Requirement already satisfied: chart-studio in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (1.1.0)
Requirement already satisfied: plotly in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from chart-studio) (5.18.0)
Requirement already satisfied: retrying>=1.3.3 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from chart-studio) (1.4.2)
Requirement already satisfied: requests in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from chart-studio) (2.31.0)
Requirement already satisfied: six in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from chart-studio) (1.16.0)
Requirement already satisfied: packaging in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from plotly->chart-studio) (22.0)
Requirement already satisfied: tenacity>=6.2.0 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from plotly->chart-studio) (8.2.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from requests->chart-studio) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from requests->chart-studio) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from requests->chart-studio) (2.0.7)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from requests->chart-studio) (3.4.7)
Requirement already satisfied: pyarrow in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (12.0.1)
Requirement already satisfied: numpy>=1.16.6 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from pyarrow) (1.21.6)
Requirement already satisfied: cufflinks in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (0.17.3)
Requirement already satisfied: pandas>=0.19.2 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from cufflinks) (1.3.5)
Requirement already satisfied: ipywidgets>=7.0.0 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from cufflinks) (8.1.8)
Requirement already satisfied: six>=1.9.0 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from cufflinks) (1.16.0)
Requirement already satisfied: plotly>=4.1.1 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from cufflinks) (5.18.0)
Requirement already satisfied: setuptools>=34.4.1 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from cufflinks) (65.6.3)
Requirement already satisfied: ipython>=5.3.0 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from cufflinks) (7.31.1)
Requirement already satisfied: colorlover>=0.2.1 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from cufflinks) (0.3.0)
Requirement already satisfied: numpy>=1.9.2 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from cufflinks) (1.21.6)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=5.3.0->cufflinks) (3.0.36)
Requirement already satisfied: matplotlib-inline in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.1.6)
Requirement already satisfied: traitlets>=4.2 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.7.1)
Requirement already satisfied: colorama in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.4.6)
Requirement already satisfied: backcall in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.2.0)
Requirement already satisfied: decorator in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.1.1)
Requirement already satisfied: pygments in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=5.3.0->cufflinks) (2.11.2)
Requirement already satisfied: jedi>=0.16 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.18.1)
Requirement already satisfied: pickleshare in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.7.5)
Requirement already satisfied: comm>=0.1.3 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (0.1.4)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (3.0.16)
Requirement already satisfied: widgetsnbextension~=4.0.14 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (4.0.15)
Requirement already satisfied: python-dateutil>=2.7.3 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from pandas>=0.19.2->cufflinks) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from pandas>=0.19.2->cufflinks) (2026.2)

Requirement already satisfied: tenacity>=6.2.0 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from plotly>=4.1.1->cufflinks) (8.2.3)
Requirement already satisfied: packaging in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from plotly>=4.1.1->cufflinks) (22.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from jedi>=0.16->ipython>=5.3.0->cufflinks) (0.8.3)
Requirement already satisfied: wcwidth in d:\users\steph\anaconda3\envs\interactive_visuals_alx\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->cufflinks) (0.2.5)

In [16]:
!jupyter nbextension enable --py widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok

In [17]:
# Standard data science helpers
import numpy as np
import pandas as pd
import scipy

# Instantiate the Plotly charting library.
import chart_studio.plotly as py
import plotly.graph_objs as go
import plotly.express as px
# We use plotly.offline as this allows us to create interactive 
# visualisations without the use of an internet connection, 
# making our notebook more distributable to others. 
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)

# The Cufflinks library allows us to directly bind 
# Pandas DataFrames to Plotly charts. 
import cufflinks as cf
# Once again, we use the Cufflinks library in offline mode. 
cf.go_offline(connected=True)
cf.set_config_file(colorscale='plotly', world_readable=True)

# Extra options. We use these to make our interactive 
# visualisations more aesthetically appealing. 
from IPython.core.display import HTML
pd.options.display.max_rows = 30
pd.options.display.max_columns = 25

# Show all code cells outputs.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

### Read in the Data

In [18]:
df = pd.read_parquet('https://github.com/WillKoehrsen/Data-Analysis/blob/master/medium/data/medium_data_2019_01_26?raw=true')
df.head()

,claps,days_since_publication,fans,link,num_responses,publication,published_date,read_ratio,read_time,reads,started_date,tags,text,title,title_word_count,type,views,word_count,claps_per_word,editing_days,<tag>Education,<tag>Data Science,<tag>Towards Data Science,<tag>Machine Learning,<tag>Python
129,2,597.301123,2,https://medium.com/p/screw-the-environment-but...,0,None,2017-06-10 14:25:00,42.17,7,70,2017-06-10 14:24:00,"[Climate Change, Economics]","Screw the Environment, but Consider Your Walle...","Screw the Environment, but Consider Your Wallet",8,published,166,1859,0.001076,0,0,0,0,0,0
125,18,589.983168,3,https://medium.com/p/the-vanquishing-of-war-pl...,0,None,2017-06-17 22:02:00,30.34,14,54,2017-06-17 22:02:00,"[Climate Change, Humanity, Optimism, History]","The Vanquishing of War, Plague and Famine Part...","The Vanquishing of War, Plague and Famine",8,published,178,3891,0.004626,0,0,0,0,0,0
132,51,577.363292,20,https://medium.com/p/capstone-project-mercedes...,0,None,2017-06-30 12:55:00,20.02,42,222,2017-06-30 12:00:00,"[Machine Learning, Python, Udacity, Kaggle]",Capstone Project: Mercedes-Benz Greener Manufa...,Capstone Project: Mercedes-Benz Greener Manufa...,7,published,1109,12025,0.004241,0,0,0,0,1,1
126,0,576.520688,0,https://medium.com/p/home-of-the-scared-5af0fe...,0,None,2017-07-01 09:08:00,35.85,9,19,2017-06-30 18:21:00,"[Politics, Books, News, Media Criticism]",Home of the Scared A review of A Culture of Fe...,Home of the Scared,4,published,53,2533,0.000000,0,0,0,0,0,0
121,0,572.533035,0,https://medium.com/p/the-triumph-of-peace-f485...,0,None,2017-07-05 08:51:00,8.47,14,5,2017-07-03 20:18:00,"[Books, Psychology, History, Humanism]",The Triumph of Peace A review of The Better An...,The Triumph of Peace,4,published,59,3892,0.000000,1,0,0,0,0,0

In [19]:
df.describe()

,claps,days_since_publication,fans,num_responses,read_ratio,read_time,reads,title_word_count,views,word_count,claps_per_word,editing_days,<tag>Education,<tag>Data Science,<tag>Towards Data Science,<tag>Machine Learning,<tag>Python
count,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000
mean,1815.263158,248.407273,352.052632,7.045113,29.074662,12.917293,6336.300752,7.127820,23404.030075,3029.120301,0.957638,20.330827,0.729323,0.609023,0.436090,0.383459,0.315789
std,2449.074661,179.370879,479.060117,9.056108,12.417670,9.510795,9007.284726,3.158475,33995.636496,2393.414456,1.846756,74.111579,0.445989,0.489814,0.497774,0.488067,0.466587
min,0.000000,1.218629,0.000000,0.000000,8.110000,1.000000,1.000000,2.000000,3.000000,163.000000,0.000000,-13.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,121.000000,74.543822,23.000000,0.000000,20.020000,8.000000,363.000000,5.000000,1375.000000,1653.000000,0.052115,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,815.000000,245.416130,136.000000,4.000000,27.060000,10.000000,2049.000000,7.000000,7608.000000,2456.000000,0.421525,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,2700.000000,376.080598,528.000000,12.000000,34.910000,14.000000,7815.000000,8.000000,30141.000000,3553.000000,1.099366,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,13600.000000,597.301123,2588.000000,59.000000,74.370000,54.000000,41978.000000,16.000000,173714.000000,15063.000000,17.891817,349.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [13]:
!jupyter nbextension install --py --sys-prefix widgetsnbextension
!jupyter nbextension enable widgetsnbextension --py --sys-prefix

Installing D:\Users\steph\anaconda3\envs\interactive_visuals_ALX\lib\site-packages\widgetsnbextension\static -> jupyter-js-widgets
Up to date: D:\Users\steph\anaconda3\envs\interactive_visuals_ALX\share\jupyter\nbextensions\jupyter-js-widgets\extension.js
Up to date: D:\Users\steph\anaconda3\envs\interactive_visuals_ALX\share\jupyter\nbextensions\jupyter-js-widgets\extension.js.LICENSE.txt
Up to date: D:\Users\steph\anaconda3\envs\interactive_visuals_ALX\share\jupyter\nbextensions\jupyter-js-widgets\extension.js.map
- Validating: ok

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable widgetsnbextension --py --sys-prefix

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok

## Interactive Visualizations

In [20]:
from ipywidgets import interact, interact_manual, widgets

In [21]:
@interact
def show_articles_more_than(column='claps', x=5000):
    display(HTML(f'<h4>Showing articles with more than {x} {column}<h4>'))
    display(df.loc[df[column] > x, ['title', 'claps', 'published_date', 'read_time', 'tags', 'views', 'reads']])

interactive(children=(Text(value='claps', description='column'), IntSlider(value=5000, description='x', max=15…

#### Example 2: Now we will add a dropdown menut to select which column to filter on while simultaneoulsy adding limits for x

In [22]:
@interact
def show_Titles_more_than(
    x=(10, 50000, 5),
    column=['read_time', 'views', 'reads']
):
    display(HTML(f'<h4>Showing articles with more than {x} {column}<h4>'))
    display(df.loc[df[column] > x, ['title', 'published_date', 'read_time', 'tags', 'views', 'reads']])

interactive(children=(IntSlider(value=25005, description='x', max=50000, min=10, step=5), Dropdown(description…

#### Example 3: Constructing a widget that quickly finds the correlation between two columns in the dataset

In [23]:
@interact
def correlations(
    column1=list(df.select_dtypes('number').columns),
    column2=list(df.select_dtypes('number').columns)
):
    print(f"Correlation: {df[column1].corr(df[column2])}")

interactive(children=(Dropdown(description='column1', options=('claps', 'days_since_publication', 'fans', 'num…

#### Example 4: Creating Interactive widgets for Plots

In [30]:
@interact
def scatter_plot(
    x=list(df.select_dtypes('number').columns),
    y=list(df.select_dtypes('number').columns)[1:]
):
    if x == y:
        print(f"Please select separate variables for X and Y")
    else:
        df.iplot(
            kind='scatter', x=x, y=y, mode='markers',
            xTitle=x.title(), yTitle=y.title(), title=f'{y.title()} vs {x.title()}'
        )
#         fig = px.scatter(df, x=x, y=y, title=f'{y.title()} vs {x.title()}')
#         fig.show(renderer="colab")

interactive(children=(Dropdown(description='x', options=('claps', 'days_since_publication', 'fans', 'num_respo…

#### Example 5: Creating a customisable heatmap of correlations

In [38]:
cscales = ['Greys', 'YlGnBu', 'Greens', 'YlOrRd', 'Bluered', 'RdBu',
            'Reds', 'Blues', 'Picnic', 'Rainbow', 'Portland', 'Jet',
            'Hot', 'Blackbody', 'Earth', 'Electric', 'Viridis', 'Cividis']

import plotly.figure_factory as ff
corrs = df.corr()

@interact
def plot_corrs(colorscale=cscales):
    figure = ff.create_annotated_heatmap(
        z=corrs.round(2).values,
        x=list(corrs.columns),
        y=list(corrs.index),
        colorscale=colorscale,
        annotation_text=corrs.round(2).values
    )
    iplot(figure)

interactive(children=(Dropdown(description='colorscale', options=('Greys', 'YlGnBu', 'Greens', 'YlOrRd', 'Blue…

#### Example 6: Trying to view various configurations for a plot that we are trying to produce

In [40]:
@interact_manual
def scatter_plot(
    x=list(df.select_dtypes('number').columns),
    y=list(df.select_dtypes('number').columns[1:]),
    theme=list(cf.themes.THEMES.keys()),
    colorscale=list(cf.colors._scales_names.keys())
):
    if x == y:
        print(f"Please select separate variables for x and y")
    else:
        df.iplot(
            kind='scatter',
            x=x,
            y=y,
            mode='markers',
            xTitle=x.title(),
            yTitle=y.title(),
            text='title',
            title=f'{y.title()} vs {x.title()}',
            theme=theme, colorscale=colorscale
        )

interactive(children=(Dropdown(description='x', options=('claps', 'days_since_publication', 'fans', 'num_respo…

#### Example 7: More ways to use widgets

In [41]:
df.set_index('published_date', inplace=True)

In [53]:
def print_articles_published(start_date, end_date):
    start_date = pd.Timestamp(start_date)
    end_date = pd.Timestamp(end_date)
    stat_df = df.loc[(df.index >= start_date) & (df.index <= end_date)].copy()
    total_words = stat_df['word_count'].sum()
    total_read_time = stat_df['read_time'].sum()
    num_articles = len(stat_df)
    print(f'According to our dataset, published by Medium.com, there are {num_articles} articles between {start_date.date()} and {end_date.date()}')
    print(f'These articles totalled {total_words:,} words and {total_read_time/60:.2f} hours to read.')

_ = interact(
    print_articles_published,
    start_date=widgets.DatePicker(value=pd.to_datetime('2018-01-01')),
    end_date=widgets.DatePicker(value=pd.to_datetime('2019-01-01'))
)

interactive(children=(DatePicker(value=Timestamp('2018-01-01 00:00:00'), description='start_date', step=1), Da…

#### Example 8: Using the Dropdown and Datepicker widgets to plot one column cumulatively up to a certain time

In [51]:
def plot_up_to(column, date):
    date = pd.Timestamp(date)
    plot_df = df.loc[df.index <= date].copy()
    plot_df[column].cumsum().iplot(
        mode='markers+lines',
        xTitle='published date',
        yTitle=column,
        title=f'cumulative {column.title()} until {date.date()}'
    )

_ = interact(
    plot_up_to, column=widgets.Dropdown(options=list(df.select_dtypes('number').columns)),
    date = widgets.DatePicker(value=pd.to_datetime('2019-01-01'))
)

interactive(children=(Dropdown(description='column', options=('claps', 'days_since_publication', 'fans', 'num_…