## This notebook consists of Interactive visualizations in Python, helping the learner understand how to create advanced custom and interactive visualizations in Python

In [1]:
!pip install scipy
!pip install ipywidgets
!pip install chart-studio
!pip install pyarrow
!pip install cufflinks

Requirement already satisfied: scipy in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (1.17.1)
Requirement already satisfied: numpy<2.7,>=1.26.4 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from scipy) (2.4.6)
Requirement already satisfied: ipywidgets in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (8.1.8)
Requirement already satisfied: comm>=0.1.3 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipywidgets) (9.11.0)
Requirement already satisfied: traitlets>=4.3.1 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: colorama>=0.4.4 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.5)
Requirement already satisfied: executing>=1.2.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure_eval in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: chart-studio in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (1.1.0)
Requirement already satisfied: plotly in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from chart-studio) (6.8.0)
Requirement already satisfied: requests in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from chart-studio) (2.33.1)
Requirement already satisfied: retrying>=1.3.3 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from chart-studio) (1.4.2)
Requirement already satisfied: six in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from chart-studio) (1.17.0)
Requirement already satisfied: narwhals>=1.15.1 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from plotly->chart-studio) (2.22.1)
Requirement already satisfied: packaging in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from plotly->chart-studio) (26.0)
Requirement already satisfied: charset_normalizer<4,>=2 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from requests->chart-studio) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from requests->chart-studio) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from requests->chart-studio) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from requests->chart-studio) (2026.5.20)
Requirement already satisfied: pyarrow in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (24.0.0)
Requirement already satisfied: cufflinks in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (0.17.3)
Requirement already satisfied: numpy>=1.9.2 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from cufflinks) (2.4.6)
Requirement already satisfied: pandas>=0.19.2 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from cufflinks) (3.0.3)
Requirement already satisfied: plotly>=4.1.1 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from cufflinks) (6.8.0)
Requirement already satisfied: six>=1.9.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from cufflinks) (1.17.0)
Requirement already satisfied: colorlover>=0.2.1 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from cufflinks) (0.3.0)
Requirement already satisfied: setuptools>=34.4.1 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from cufflinks) (82.0.1)
Requirement already satisfied: ipython>=5.3.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from cufflinks) (9.11.0)
Requirement already satisfied: ipywidgets>=7.0.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from cufflinks) (8.1.8)
Requirement already satisfied: colorama>=0.4.4 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=5.3.0->cufflinks) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=5.3.0->cufflinks) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=5.3.0->cufflinks) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=5.3.0->cufflinks) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=5.3.0->cufflinks) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=5.3.0->cufflinks) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=5.3.0->cufflinks) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=5.3.0->cufflinks) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipython>=5.3.0->cufflinks) (5.14.3)
Requirement already satisfied: wcwidth in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.3.0->cufflinks) (0.2.14)
Requirement already satisfied: comm>=0.1.3 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (3.0.16)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from jedi>=0.18.2->ipython>=5.3.0->cufflinks) (0.8.5)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from pandas>=0.19.2->cufflinks) (2.9.0.post0)
Requirement already satisfied: tzdata in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from pandas>=0.19.2->cufflinks) (2026.2)
Requirement already satisfied: narwhals>=1.15.1 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from plotly>=4.1.1->cufflinks) (2.22.1)
Requirement already satisfied: packaging in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from plotly>=4.1.1->cufflinks) (26.0)
Requirement already satisfied: executing>=1.2.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.3.0->cufflinks) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.3.0->cufflinks) (3.0.1)
Requirement already satisfied: pure_eval in D:\Users\steph\anaconda3\envs\alx_python_track\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.3.0->cufflinks) (0.2.3)

In [3]:
!jupyter nbextension enable --py widgetsnbextension

usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json] [--debug]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: console contrib dejavu events execute kernel kernelspec
lab labextension labhub migrate nbclassic nbconvert nbextensions_configurator
notebook qtconsole run script server troubleshoot trust

Jupyter command `jupyter-nbextension` not found.

In [4]:
import numpy as np
import pandas as pd
import scipy

# instantiate the plotly charting library
import chart_studio.plotly as py
import plotly.graph_objs as go
import plotly.express as px

from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)

import cufflinks as cf
cf.go_offline(connected=True)
cf.set_config_file(colorscale='plotly', world_readable=True)

from IPython.core.display import HTML
pd.options.display.max_rows = 30
pd.options.display.max_columns = 25

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [5]:
df = pd.read_parquet('https://github.com/WillKoehrsen/Data-Analysis/blob/master/medium/data/medium_data_2019_01_26?raw=true')

df.head()

,claps,days_since_publication,fans,link,num_responses,publication,published_date,read_ratio,read_time,reads,started_date,tags,text,title,title_word_count,type,views,word_count,claps_per_word,editing_days,<tag>Education,<tag>Data Science,<tag>Towards Data Science,<tag>Machine Learning,<tag>Python
129,2,597.301123,2,https://medium.com/p/screw-the-environment-but...,0,None,2017-06-10 14:25:00+00:00,42.17,7,70,2017-06-10 14:24:00+00:00,"[Climate Change, Economics]","Screw the Environment, but Consider Your Walle...","Screw the Environment, but Consider Your Wallet",8,published,166,1859,0.001076,0,0,0,0,0,0
125,18,589.983168,3,https://medium.com/p/the-vanquishing-of-war-pl...,0,None,2017-06-17 22:02:00+00:00,30.34,14,54,2017-06-17 22:02:00+00:00,"[Climate Change, Humanity, Optimism, History]","The Vanquishing of War, Plague and Famine Part...","The Vanquishing of War, Plague and Famine",8,published,178,3891,0.004626,0,0,0,0,0,0
132,51,577.363292,20,https://medium.com/p/capstone-project-mercedes...,0,None,2017-06-30 12:55:00+00:00,20.02,42,222,2017-06-30 12:00:00+00:00,"[Machine Learning, Python, Udacity, Kaggle]",Capstone Project: Mercedes-Benz Greener Manufa...,Capstone Project: Mercedes-Benz Greener Manufa...,7,published,1109,12025,0.004241,0,0,0,0,1,1
126,0,576.520688,0,https://medium.com/p/home-of-the-scared-5af0fe...,0,None,2017-07-01 09:08:00+00:00,35.85,9,19,2017-06-30 18:21:00+00:00,"[Politics, Books, News, Media Criticism]",Home of the Scared A review of A Culture of Fe...,Home of the Scared,4,published,53,2533,0.000000,0,0,0,0,0,0
121,0,572.533035,0,https://medium.com/p/the-triumph-of-peace-f485...,0,None,2017-07-05 08:51:00+00:00,8.47,14,5,2017-07-03 20:18:00+00:00,"[Books, Psychology, History, Humanism]",The Triumph of Peace A review of The Better An...,The Triumph of Peace,4,published,59,3892,0.000000,1,0,0,0,0,0

### Interactive Visualisations

In [11]:
from ipywidgets import interact, interact_manual, widgets
from IPython.display import HTML, display

In [7]:
@interact
def show_articles_more_than(column='claps', x=5000):
    display(HTML(f'<h4>Showing articles with more than {x} {column}</h4>'))
    display(df.loc[df[column] > x, ['title', 'claps', 'published_date', 'read_time', 'tags', 'views', 'reads']])

,title,claps,published_date,read_time,tags,views,reads
100,Stock Prediction in Python,7300,2018-01-19 15:30:00+00:00,12,"[Machine Learning, Data Science, Programming, ...",134699,41978
88,Python is the Perfect Tool for any Problem,12900,2018-02-04 09:12:00+00:00,3,"[Python, Programming, Education, Data Science,...",48157,30099
89,Markov Chain Monte Carlo in Python,5100,2018-02-09 22:29:00+00:00,12,"[Machine Learning, Data Science, Programming, ...",57830,16735
83,Bayes’ Rule Applied,6000,2018-02-14 11:27:00+00:00,9,"[Statistics, Programming, Education, Data Anal...",35505,11491
82,Beyond Accuracy: Precision and Recall,7000,2018-03-03 11:10:00+00:00,11,"[Machine Learning, Data Science, Education, St...",128661,26327
84,Controlling the Web with Python,7000,2018-03-10 16:16:00+00:00,9,"[Python, Education, Programming, Internet, Tow...",65054,14614
75,Introduction to Bayesian Linear Regression,5500,2018-04-13 20:38:00+00:00,10,"[Data Science, Education, Statistics, Learning...",58471,19805
65,"Web Scraping, Regular Expressions, and Data Vi...",8000,2018-04-28 15:27:00+00:00,7,"[Data Science, Programming, Education, Compute...",68317,21607
69,A Complete Machine Learning Project Walk-Throu...,13600,2018-05-16 12:33:00+00:00,15,"[Machine Learning, Education, Data Science, Py...",124970,23587
62,Machine Learning Kaggle Competition Part One: ...,6400,2018-05-28 11:39:00+00:00,12,"[Data Science, Machine Learning, Towards Data ...",43577,10398
66,Automated Feature Engineering in Python,8500,2018-06-02 10:01:00+00:00,11,"[Machine Learning, Towards Data Science, Data ...",114762,25139
63,A Feature Selection Tool for Machine Learning ...,5500,2018-06-22 10:12:00+00:00,10,"[Machine Learning, Python, Education, Programm...",80618,20592
19,The Next Level of Data Visualization in Python,7600,2019-01-08 22:09:00+00:00,8,"[Data Science, Data Visualization, Python, Edu...",71225,24002

interactive(children=(Text(value='claps', description='column'), IntSlider(value=5000, description='x', max=15…

In [13]:
@interact
def show_titles_more_than(x=(10, 50000, 10), column=['read_time', 'views', 'reads']):
    display(HTML(f'<h4>Showing articles with more than {x} {column}</h4>'))
    display(df.loc[df[column] > x, ['title', 'published_date', 'read_time', 'tags', 'views', 'reads']])

Empty DataFrame
Columns: [title, published_date, read_time, tags, views, reads]
Index: []

interactive(children=(IntSlider(value=25000, description='x', max=50000, min=10, step=10), Dropdown(descriptio…

7.5.5