<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/Python-Notebook-Banners/Code_challenge.png"  style="display: block; margin-left: auto; margin-right: auto;";/>
</div>

# Code challenge: Random forest regression
© ExploreAI Academy

In this code challenge, we'll test our knowledge of how to create an ensemble model known as a random forest. We will train this new model using the world population data.

⚠️ **Note that this code challenge is graded and will contribute to your overall marks for this module. Submit this notebook for grading. Note that the names of the functions are different in this notebook. Transfer the code in your notebook to this submission notebook**

### Instructions

- **Do not add or remove cells in this notebook. Do not edit or remove the `### START FUNCTION` or `### END FUNCTION` comments. Do not add any code outside of the functions you are required to edit. Doing any of this will lead to a mark of 0%!**

- Answer the questions according to the specifications provided.

- Use the given cell in each question to see if your function matches the expected outputs.

- Do not hard-code answers to the questions.

- The use of StackOverflow, Google, and other online tools is permitted. However, copying a fellow student's code is not permissible and is considered a breach of the Honour code. Doing this will result in a mark of 0%.

### Imports

In [2]:
import numpy as np
import pandas as pd
from numpy import array
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

In [3]:
population_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/world_population.csv', index_col='Country Code')
meta_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/metadata.csv', index_col='Country Code')

In [4]:
population_df.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Country Code,,,,,,,,,,,,,,,,,,,,,
ABW,54211.0,55438.0,56225.0,56695.0,57032.0,57360.0,57715.0,58055.0,58386.0,58726.0,...,101353.0,101453.0,101669.0,102053.0,102577.0,103187.0,103795.0,104341.0,104822.0,105264.0
AFG,8996351.0,9166764.0,9345868.0,9533954.0,9731361.0,9938414.0,10152331.0,10372630.0,10604346.0,10854428.0,...,27294031.0,28004331.0,28803167.0,29708599.0,30696958.0,31731688.0,32758020.0,33736494.0,34656032.0,35530081.0
AGO,5643182.0,5753024.0,5866061.0,5980417.0,6093321.0,6203299.0,6309770.0,6414995.0,6523791.0,6642632.0,...,21759420.0,22549547.0,23369131.0,24218565.0,25096150.0,25998340.0,26920466.0,27859305.0,28813463.0,29784193.0
ALB,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,1914573.0,1965598.0,2022272.0,2081695.0,...,2947314.0,2927519.0,2913021.0,2905195.0,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0
AND,13411.0,14375.0,15370.0,16412.0,17469.0,18549.0,19647.0,20758.0,21890.0,23058.0,...,83861.0,84462.0,84449.0,83751.0,82431.0,80788.0,79223.0,78014.0,77281.0,76965.0

In [5]:
meta_df.head()

,Region,Income Group,Special Notes
Country Code,,,
ABW,Latin America & Caribbean,High income,Mining is included in agriculture\r\r\r\nElect...
AFG,South Asia,Low income,Fiscal year end: March 20; reporting period fo...
AGO,Sub-Saharan Africa,Lower middle income,NaN
ALB,Europe & Central Asia,Upper middle income,NaN
AND,Europe & Central Asia,High income,WB-3 code changed from ADO to AND to align wit...

In [6]:
meta_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 217 entries, ABW to ZWE
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Region         217 non-null    object
 1   Income Group   217 non-null    object
 2   Special Notes  116 non-null    object
dtypes: object(3)
memory usage: 6.8+ KB

In [7]:
population_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 217 entries, ABW to ZWE
Data columns (total 58 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1960    214 non-null    float64
 1   1961    214 non-null    float64
 2   1962    214 non-null    float64
 3   1963    214 non-null    float64
 4   1964    214 non-null    float64
 5   1965    214 non-null    float64
 6   1966    214 non-null    float64
 7   1967    214 non-null    float64
 8   1968    214 non-null    float64
 9   1969    214 non-null    float64
 10  1970    214 non-null    float64
 11  1971    214 non-null    float64
 12  1972    214 non-null    float64
 13  1973    214 non-null    float64
 14  1974    214 non-null    float64
 15  1975    214 non-null    float64
 16  1976    214 non-null    float64
 17  1977    214 non-null    float64
 18  1978    214 non-null    float64
 19  1979    214 non-null    float64
 20  1980    214 non-null    float64
 21  1981    214 non-null    float64
 22  1982    214 non-null    float64
 23  1983    214 non-null    float64
 24  1984    214 non-null    float64
 25  1985    214 non-null    float64
 26  1986    214 non-null    float64
 27  1987    214 non-null    float64
 28  1988    214 non-null    float64
 29  1989    214 non-null    float64
 30  1990    216 non-null    float64
 31  1991    216 non-null    float64
 32  1992    215 non-null    float64
 33  1993    215 non-null    float64
 34  1994    215 non-null    float64
 35  1995    216 non-null    float64
 36  1996    216 non-null    float64
 37  1997    216 non-null    float64
 38  1998    217 non-null    float64
 39  1999    217 non-null    float64
 40  2000    217 non-null    float64
 41  2001    217 non-null    float64
 42  2002    217 non-null    float64
 43  2003    217 non-null    float64
 44  2004    217 non-null    float64
 45  2005    217 non-null    float64
 46  2006    217 non-null    float64
 47  2007    217 non-null    float64
 48  2008    217 non-null    float64
 49  2009    217 non-null    float64
 50  2010    217 non-null    float64
 51  2011    217 non-null    float64
 52  2012    216 non-null    float64
 53  2013    216 non-null    float64
 54  2014    216 non-null    float64
 55  2015    216 non-null    float64
 56  2016    216 non-null    float64
 57  2017    216 non-null    float64
dtypes: float64(58)
memory usage: 100.0+ KB

### Question 1

The world population data spans from 1960 to 2017. We'd like to build a predictive model that can give us the best guess at what the world population in a given year was. However, we want to compute this estimate for only _countries within a given income group_. 

First, however, we need to organise our data such that the sklearn's `RandomForestRegressor` class can train on our data. To do this, we will write a function that takes as input an income group and returns a 2-d numpy array that contains the year and the measured population.

_**Function Specifications:**_
* Should take a `str` argument, called `income_group_name` as input and return a numpy `array` type as output.
* Set the default argument of `income_group_name` to equal `'Low income'`.
* If the specified value of `income_group_name` does not exist, the function must raise a `ValueError`.
* The array should only have two columns containing the year and the population, in other words, it should have a shape `(?, 2)` where `?` is the length of the data.
* The values within the array should be of type `np.int64`. 

_**Further Reading:**_

Data types are associated with memory allocation. As such, your choice of data type affects the precision of computations in your program. For example, the `np.int` data type in numpy can only store values between -2147483648 to 2147483647 and assigning values outside this range for variables of this data type may cause run-time errors. To avoid this, we can use data types with larger memory capacity e.g. `np.int64`.

https://docs.scipy.org/doc/numpy/user/basics.types.html

In [21]:
income_group = meta_df.loc[meta_df['Income Group'] == 'High income']

income_group.index
# low_income.index
population_df_filtered = population_df.loc[population_df.index.isin(income_group.index)]

population_df_filtered

results = []

for year in population_df_filtered.columns:
    yearly_population = population_df_filtered[year]
    total_population = yearly_population.sum()
    
    year = np.int64(year)

    results.append([
        year,
        total_population
    ])
    
results = np.array(results)
# low_income['Country code']
# low_income.loc[low_income['Country Code'] == 'AFG']

In [47]:
type(meta_df['Income Group'])

pandas.core.series.Series

In [22]:
results

array([[1.96000000e+03, 7.69889923e+08],
       [1.96100000e+03, 7.81225329e+08],
       [1.96200000e+03, 7.91207437e+08],
       [1.96300000e+03, 8.01108277e+08],
       [1.96400000e+03, 8.10900987e+08],
       [1.96500000e+03, 8.20309686e+08],
       [1.96600000e+03, 8.29088382e+08],
       [1.96700000e+03, 8.37479954e+08],
       [1.96800000e+03, 8.44905494e+08],
       [1.96900000e+03, 8.54059674e+08],
       [1.97000000e+03, 8.62276721e+08],
       [1.97100000e+03, 8.71169187e+08],
       [1.97200000e+03, 8.80246152e+08],
       [1.97300000e+03, 8.88486025e+08],
       [1.97400000e+03, 8.97803169e+08],
       [1.97500000e+03, 9.06573084e+08],
       [1.97600000e+03, 9.13843314e+08],
       [1.97700000e+03, 9.21330504e+08],
       [1.97800000e+03, 9.28906293e+08],
       [1.97900000e+03, 9.36836246e+08],
       [1.98000000e+03, 9.44587066e+08],
       [1.98100000e+03, 9.52368316e+08],
       [1.98200000e+03, 9.59759971e+08],
       [1.98300000e+03, 9.66754949e+08],
       [1.98400000e+03, 9.73423742e+08],
       [1.98500000e+03, 9.80143630e+08],
       [1.98600000e+03, 9.87194728e+08],
       [1.98700000e+03, 9.94242786e+08],
       [1.98800000e+03, 1.00142146e+09],
       [1.98900000e+03, 1.00903689e+09],
       [1.99000000e+03, 1.01709267e+09],
       [1.99100000e+03, 1.02534541e+09],
       [1.99200000e+03, 1.03194981e+09],
       [1.99300000e+03, 1.04034948e+09],
       [1.99400000e+03, 1.04812144e+09],
       [1.99500000e+03, 1.05729059e+09],
       [1.99600000e+03, 1.06463066e+09],
       [1.99700000e+03, 1.07196957e+09],
       [1.99800000e+03, 1.07892776e+09],
       [1.99900000e+03, 1.08599267e+09],
       [2.00000000e+03, 1.09282568e+09],
       [2.00100000e+03, 1.10029397e+09],
       [2.00200000e+03, 1.10783636e+09],
       [2.00300000e+03, 1.11539052e+09],
       [2.00400000e+03, 1.12332504e+09],
       [2.00500000e+03, 1.13142628e+09],
       [2.00600000e+03, 1.14008483e+09],
       [2.00700000e+03, 1.14923899e+09],
       [2.00800000e+03, 1.15896529e+09],
       [2.00900000e+03, 1.16771241e+09],
       [2.01000000e+03, 1.17564923e+09],
       [2.01100000e+03, 1.18145134e+09],
       [2.01200000e+03, 1.18879610e+09],
       [2.01300000e+03, 1.19621292e+09],
       [2.01400000e+03, 1.20381990e+09],
       [2.01500000e+03, 1.21125204e+09],
       [2.01600000e+03, 1.21862961e+09],
       [2.01700000e+03, 1.22551423e+09]])

In [65]:
### START FUNCTION
def get_total_pop_by_income(income_group_name='Low income'):
    # your code here
    if income_group_name not in meta_df['Income Group'].values:
        raise ValueError('Invalid Input for Income Group')
    
    income_group = meta_df.loc[meta_df['Income Group'] == income_group_name]
    
    population_df_filtered = population_df.loc[population_df.index.isin(income_group.index)]

    population_df_filtered

    results = []

    for year in population_df_filtered.columns:
        yearly_population = population_df_filtered[year]
        total_population = yearly_population.sum()

        results.append([
            int(year),
            total_population
        ])

    results = np.array(results).astype(np.int64)
    
    return results

### END FUNCTION

In [66]:
data = get_total_pop_by_income('High income')

_**Expected Outputs:**_
```python
get_total_pop_by_income('High income')
```
> ```
array([[      1960,  769889923],
       [      1961,  781225329],
       [      1962,  791207437],
       [      1963,  801108277],
       ...
       [      2015, 1211252041],
       [      2016, 1218629612],
       [      2017, 1225514228]])
```

In [67]:
data

array([[      1960,  769889923],
       [      1961,  781225329],
       [      1962,  791207437],
       [      1963,  801108277],
       [      1964,  810900987],
       [      1965,  820309686],
       [      1966,  829088382],
       [      1967,  837479954],
       [      1968,  844905494],
       [      1969,  854059674],
       [      1970,  862276721],
       [      1971,  871169187],
       [      1972,  880246152],
       [      1973,  888486025],
       [      1974,  897803169],
       [      1975,  906573084],
       [      1976,  913843314],
       [      1977,  921330504],
       [      1978,  928906293],
       [      1979,  936836246],
       [      1980,  944587066],
       [      1981,  952368316],
       [      1982,  959759971],
       [      1983,  966754949],
       [      1984,  973423742],
       [      1985,  980143630],
       [      1986,  987194728],
       [      1987,  994242786],
       [      1988, 1001421456],
       [      1989, 1009036892],
       [      1990, 1017092667],
       [      1991, 1025345408],
       [      1992, 1031949811],
       [      1993, 1040349480],
       [      1994, 1048121445],
       [      1995, 1057290586],
       [      1996, 1064630661],
       [      1997, 1071969568],
       [      1998, 1078927765],
       [      1999, 1085992668],
       [      2000, 1092825678],
       [      2001, 1100293969],
       [      2002, 1107836355],
       [      2003, 1115390519],
       [      2004, 1123325037],
       [      2005, 1131426281],
       [      2006, 1140084827],
       [      2007, 1149238990],
       [      2008, 1158965286],
       [      2009, 1167712409],
       [      2010, 1175649232],
       [      2011, 1181451343],
       [      2012, 1188796100],
       [      2013, 1196212921],
       [      2014, 1203819897],
       [      2015, 1211252041],
       [      2016, 1218629612],
       [      2017, 1225514228]], dtype=int64)

### Question 2

Now that we have have our data, we need to split this into a set of variables we will be training on, and the set of variables that we will make our predictions on.

Sklearn has a bunch of built-in functionality for creating training and testing sets. Our task is to implement a k-fold cross validation split of the data using sklearn's `KFold` [class](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html) (which has already been imported into this notebook for your convenience). 

Using this knowledge, write a function which uses sklearn's `KFold` [class](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html) internally, and that will take as input a 2-d numpy array and an integer `K` corresponding to the number of splits. This function will then return a list of tuples of length `K`. Each tuple in this list should consist of a `train_indices` list and a `test_indices` list containing the training/testing data point indices for that particular $K^{th}$ split.

_**Function Specifications:**_
* Should take a 2-d numpy `array` and an integer `K` as input.
* Should use sklearn's `KFold` [class](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html).
* Should return a list of `K` `tuples` containing a list of training and testing indices corresponding to the data points that belong to a particular split. For example, given an array called `data` and an integer `K`, the function should return: 
>```
data_indices = [(list_of_train_indices_for_split_1, list_of_test_indices_for_split_1)
                  (list_of_train_indices_for_split_2, list_of_test_indices_for_split_2)
                  (list_of_train_indices_for_split_3, list_of_test_indices_for_split_3)
                                                   ...
                                                   ...
                  (list_of_train_indices_for_split_K, list_of_test_indices_for_split_K)]
```

* The `shuffle` argument in the KFold object should be set to `False`.

**_Hint_**: To see an example of how to use the `KFold` object enter `help(KFold)` in a new notebook cell

In [70]:
type(data)

numpy.ndarray

In [89]:
### START FUNCTION
def sklearn_kfold_split(data,K):
    # your code here
    kf = KFold(
        n_splits=K,
        shuffle=False
    )
    
    splits = []
    
    for train_idx, test_idx in kf.split(data):
        splits.append((train_idx, test_idx))
        
    return splits

### END FUNCTION

In [90]:
data = get_total_pop_by_income('High income');
sklearn_kfold_split(data,4)

[(array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
         32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
         49, 50, 51, 52, 53, 54, 55, 56, 57]),
  array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 30, 31,
         32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
         49, 50, 51, 52, 53, 54, 55, 56, 57]),
  array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 44, 45, 46, 47,
         48, 49, 50, 51, 52, 53, 54, 55, 56, 57]),
  array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43])),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
         34, 35, 36, 37, 38, 39, 40, 41, 42, 43]),
  array([44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57]))]

_**Expected Outputs:**_
```python
data = get_total_pop_by_income('High income')
sklearn_kfold_split(data,4)
```
> ```
[(array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
         32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
         49, 50, 51, 52, 53, 54, 55, 56, 57]),
  array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 30, 31,
         32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
         49, 50, 51, 52, 53, 54, 55, 56, 57]),
  array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 44, 45, 46, 47,
         48, 49, 50, 51, 52, 53, 54, 55, 56, 57]),
  array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43])),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
         34, 35, 36, 37, 38, 39, 40, 41, 42, 43]),
  array([44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57]))]
 ```

### Question 3

Now that we have formatted our data, we can fit a model using sklearn's `RandomForestRegressor` class. We'll write a function that will take as input the data indices (consisting of the train and test indices for each split) that we created in the last question, train a different `RandomForestRegressor` on each split and return the model that obtains the best testing set performance across all K splits.

**Important Note:** Due to the random initialisation process used within sklearn's `RandomForestRegressor` class, you will need to fix the value of the `random_state` argument in order to get repeatable and predictable results.

_**Function Specifications:**_
* Should take a 2-d numpy array (i.e. the data) and `data_indices` (a list of `(train_indices,test_indices)` tuples) as input.
* For each `(train_indices,test_indices)` tuple in `data_indices` the function should:
    * Train a new `RandomForestRegressor` model on the portion of data indexed by `train_indices`
    * Evaluate the trained `RandomForestRegressor` model on the portion of data indexed by `test_indices` using the **mean squared error** (which has also been imported for your convenience).
* After training and evaluating the `RandomForestRegressor` models, the function should return the `RandomForestRegressor` model that obtained the highest testing set `mean_square_error` over its allocated data split across all trained models. 
* The trained `RandomForestRegressor` models should be trained with `random_state` equal `42`, all other parameters should be left as default.

**_Hint_**: for each tuple in the `data_indices` list, you can obtain `X_train`,`X_test`, `y_train`, `y_test` as follows:  
>```
    X_train, y_train = data[train_indices,0],data[train_indices,1]
    X_test, y_test = data[test_indices,0],data[test_indices,1]
```

In [122]:
### START FUNCTION
def best_k_model(data,data_indices):
    # your code here
    X = data[:, 0].reshape(-1, 1)
    y = data[:, 1]
    
    models = []
    
    for train_idx, test_idx in data_indices:
        model = RandomForestRegressor(random_state=42)
        
        X_train = X[train_idx]
        X_test = X[test_idx]
        
        y_train = y[train_idx]
        y_test = y[test_idx]
        
        model.fit(X_train, y_train)
        
        y_pred = model.predict(X_test)
        
        mse = mean_squared_error(y_test, y_pred)
        
        models.append((model, mse))
    
    best_model = max(models, key=lambda item: item[1])
    
    return best_model[0]

### END FUNCTION

In [123]:
data = get_total_pop_by_income('High income')
data_indices = sklearn_kfold_split(data,5)

best_model = best_k_model(data,data_indices)
best_model.predict([[1960]])

array([8.85170916e+08])

_**Expected Outputs:**_
```python
best_model.predict([[1960]]) == array([8.85170916e+08])
```

#  

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/ExploreAI_logos/EAI_Blue_Dark.png"  style="width:200px";/>
</div>