## Examples: Introduction to binary classification using logistic regression

#### In this train, we'll delve into the application of logistic regression for binary classification, using practical examples to demonstrate how this model distinguishes between two classes.

### Learning objectives
#### By the end of this train, you should be able to:
#### - Understand logistic regression
#### - Implement a logistic regression model using `sklearn`

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# Read data in and view first few entries
df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/classification_sprint/claims_data.csv')
df.head()

,age,sex,bmi,steps,children,smoker,region,insurance_claim,claim_amount
0,19,female,27.900,3009,0,yes,southwest,yes,16884.9240
1,18,male,33.770,3008,1,no,southeast,yes,1725.5523
2,28,male,33.000,3009,3,no,southeast,no,0.0000
3,33,male,22.705,10009,0,no,northwest,no,0.0000
4,32,male,28.880,8010,0,no,northwest,yes,3866.8552

In [3]:
df['insurance_claim'].unique()

array(['yes', 'no'], dtype=object)

### Preprocessing

In [6]:
# labels
y = df['insurance_claim']

# features
X = df.drop('insurance_claim', axis=1)

In [7]:
# Transforming the features
X_transformed = pd.get_dummies(X, drop_first=True)

In [8]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X_transformed,
    y,
    test_size=0.2,
    random_state=50
)

### Training

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
lr = LogisticRegression()

In [14]:
lr.fit(X_train, y_train)

LogisticRegression()

In [21]:
lr.intercept_[0]

-9.641664189625324e-05

In [26]:
lr.coef_

array([[-2.56061195e-03, -1.81892895e-03, -4.55628470e-03,
        -2.07820639e-04,  3.80411585e-02, -7.01596680e-06,
        -1.29220095e-05, -2.32788899e-05, -1.37761720e-05,
         4.82242766e-06]])

In [27]:
lr.coef_.T

array([[-2.56061195e-03],
       [-1.81892895e-03],
       [-4.55628470e-03],
       [-2.07820639e-04],
       [ 3.80411585e-02],
       [-7.01596680e-06],
       [-1.29220095e-05],
       [-2.32788899e-05],
       [-1.37761720e-05],
       [ 4.82242766e-06]])

In [28]:
coeff_df = pd.DataFrame(
    lr.coef_.T,
    X_transformed.columns,
    columns=['Coefficient']
)

coeff_df

                  Coefficient
age                 -0.002561
bmi                 -0.001819
steps               -0.004556
children            -0.000208
claim_amount         0.038041
sex_male            -0.000007
smoker_yes          -0.000013
region_northwest    -0.000023
region_southeast    -0.000014
region_southwest     0.000005

In [29]:
X_transformed

,age,bmi,steps,children,claim_amount,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,3009,0,16884.9240,0,1,0,0,1
1,18,33.770,3008,1,1725.5523,1,0,0,1,0
2,28,33.000,3009,3,0.0000,1,0,0,1,0
3,33,22.705,10009,0,0.0000,1,0,1,0,0
4,32,28.880,8010,0,3866.8552,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
1333,50,30.970,4008,3,0.0000,1,0,1,0,0
1334,18,31.920,3003,0,2205.9808,0,0,0,0,0
1335,18,36.850,3008,0,1629.8335,0,0,0,1,0
1336,21,25.800,8009,0,0.0000,0,0,0,0,1
1337,61,29.070,8008,0,29141.3603,0,1,1,0,0

In [30]:
X_transformed.columns

Index(['age', 'bmi', 'steps', 'children', 'claim_amount', 'sex_male',
       'smoker_yes', 'region_northwest', 'region_southeast',
       'region_southwest'],
      dtype='object')

### Prediction time

In [31]:
pred_lr = lr.predict(X_test)

In [32]:
pred_lr

array(['no', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes',
       'yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'yes',
       'no', 'yes', 'no', 'yes', 'no', 'yes', 'no', 'yes', 'no', 'no',
       'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no',
       'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes',
       'yes', 'no', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'yes', 'yes',
       'yes', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes',
       'yes', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes', 'no',
       'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'no', 'yes', 'no',
       'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes',
       'no', 'yes', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'yes', 'yes',
       'yes', 'no', 'yes', 'no', 'no', 'yes', 'no', 'yes', 'yes', 'no',
       'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes',
       'yes', 'no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'no',
       'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes',
       'yes', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'yes',
       'yes', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no',
       'yes', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'no',
       'no', 'yes', 'no', 'yes', 'no', 'no', 'yes', 'no', 'yes', 'yes',
       'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'no',
       'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'no',
       'yes', 'yes', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'no', 'yes', 'no', 'yes', 'yes', 'no', 'no', 'yes', 'yes',
       'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no', 'yes',
       'yes', 'yes', 'no', 'no', 'no', 'yes', 'yes', 'no', 'yes', 'no',
       'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'yes'], dtype=object)