In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

In [62]:
population_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/world_population.csv', index_col='Country Code')
population_df.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Country Code,,,,,,,,,,,,,,,,,,,,,
ABW,54211.0,55438.0,56225.0,56695.0,57032.0,57360.0,57715.0,58055.0,58386.0,58726.0,...,101353.0,101453.0,101669.0,102053.0,102577.0,103187.0,103795.0,104341.0,104822.0,105264.0
AFG,8996351.0,9166764.0,9345868.0,9533954.0,9731361.0,9938414.0,10152331.0,10372630.0,10604346.0,10854428.0,...,27294031.0,28004331.0,28803167.0,29708599.0,30696958.0,31731688.0,32758020.0,33736494.0,34656032.0,35530081.0
AGO,5643182.0,5753024.0,5866061.0,5980417.0,6093321.0,6203299.0,6309770.0,6414995.0,6523791.0,6642632.0,...,21759420.0,22549547.0,23369131.0,24218565.0,25096150.0,25998340.0,26920466.0,27859305.0,28813463.0,29784193.0
ALB,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,1914573.0,1965598.0,2022272.0,2081695.0,...,2947314.0,2927519.0,2913021.0,2905195.0,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0
AND,13411.0,14375.0,15370.0,16412.0,17469.0,18549.0,19647.0,20758.0,21890.0,23058.0,...,83861.0,84462.0,84449.0,83751.0,82431.0,80788.0,79223.0,78014.0,77281.0,76965.0

In [18]:
population_df.describe().T

,count,mean,std,min,25%,50%,75%,max
1960,214.0,1.408851e+07,5.767208e+07,4279.0,237035.00,2401711.0,8045923.50,6.670700e+08
1961,214.0,1.427893e+07,5.775221e+07,4453.0,238495.25,2442783.5,8189191.50,6.603300e+08
1962,214.0,1.452514e+07,5.848146e+07,4566.0,241677.00,2492448.0,8280730.00,6.657700e+08
1963,214.0,1.482807e+07,5.980582e+07,4656.0,247233.00,2537329.5,8390127.00,6.823350e+08
1964,214.0,1.513290e+07,6.111311e+07,4748.0,253358.00,2585682.5,8508820.25,6.983550e+08
1965,214.0,1.544440e+07,6.247168e+07,4841.0,260197.00,2630378.0,8615307.75,7.151850e+08
1966,214.0,1.577058e+07,6.401060e+07,4936.0,267900.00,2679029.5,8778726.75,7.354000e+08
1967,214.0,1.609526e+07,6.550343e+07,5033.0,276326.50,2740750.0,8929183.00,7.545500e+08
1968,214.0,1.642355e+07,6.704857e+07,5161.0,284974.50,2797295.0,9110254.50,7.745100e+08
1969,214.0,1.677135e+07,6.870634e+07,5303.0,292655.50,2863830.5,9324390.50,7.960250e+08
1970,214.0,1.712276e+07,7.042486e+07,5450.0,299388.25,2943664.5,9534414.75,8.183150e+08
1971,214.0,1.748386e+07,7.219607e+07,5601.0,301924.50,3006220.5,9708589.75,8.411050e+08
1972,214.0,1.784147e+07,7.388575e+07,5756.0,306348.75,3065883.5,9828502.75,8.620300e+08
1973,214.0,1.819498e+07,7.553272e+07,5915.0,308728.00,3133737.5,9898594.50,8.819400e+08
1974,214.0,1.855157e+07,7.711865e+07,6078.0,311232.75,3201206.0,10054243.75,9.003500e+08
1975,214.0,1.889989e+07,7.858891e+07,6291.0,315662.00,3258082.5,10273025.50,9.163950e+08
1976,214.0,1.923881e+07,7.997127e+07,6530.0,319513.25,3306332.0,10480492.50,9.306850e+08
1977,214.0,1.957658e+07,8.128836e+07,6778.0,320488.25,3353935.5,10533495.75,9.434550e+08
1978,214.0,1.992002e+07,8.261876e+07,7035.0,332969.00,3418809.0,10602241.25,9.561650e+08
1979,214.0,2.027208e+07,8.397573e+07,7264.0,347629.75,3474921.0,10665808.25,9.690050e+08
1980,214.0,2.062773e+07,8.531787e+07,7488.0,360610.25,3515301.0,10779301.50,9.812350e+08
1981,214.0,2.099265e+07,8.670354e+07,7592.0,367448.75,3569400.0,11016165.75,9.938850e+08
1982,214.0,2.137124e+07,8.821694e+07,7717.0,370461.50,3642349.5,11378099.50,1.008630e+09
1983,214.0,2.175327e+07,8.974150e+07,7854.0,372667.00,3726494.5,11789109.75,1.023310e+09
1984,214.0,2.213403e+07,9.121640e+07,8005.0,377249.25,3831557.5,12031750.75,1.036825e+09
1985,214.0,2.252196e+07,9.273658e+07,8173.0,383460.00,3932040.5,12081533.50,1.051040e+09
1986,214.0,2.292159e+07,9.434389e+07,8353.0,406819.50,4030545.5,12188341.25,1.066790e+09
1987,214.0,2.333121e+07,9.603315e+07,8554.0,428999.00,4127151.5,12321299.00,1.084035e+09
1988,214.0,2.374511e+07,9.774561e+07,8755.0,449146.00,4213944.0,12536536.50,1.101630e+09
1989,214.0,2.415968e+07,9.943414e+07,8947.0,466675.00,4278484.0,12789458.75,1.118650e+09
1990,216.0,2.438825e+07,1.006518e+08,9003.0,491059.50,4352129.5,12645161.25,1.135185e+09
1991,216.0,2.479183e+07,1.022733e+08,9053.0,504196.50,4401540.0,13109553.75,1.150780e+09
1992,215.0,2.529789e+07,1.040565e+08,9109.0,509302.00,4502363.0,13826132.00,1.164970e+09
1993,215.0,2.569290e+07,1.055773e+08,9156.0,512341.50,4623280.0,14327117.00,1.178440e+09
1994,215.0,2.608263e+07,1.070984e+08,9190.0,511799.00,4651225.0,14954865.00,1.191835e+09
1995,216.0,2.635429e+07,1.083691e+08,9230.0,514521.50,4701500.0,15355241.25,1.204855e+09
1996,216.0,2.673700e+07,1.098648e+08,9256.0,523575.25,4708576.0,15542347.00,1.217550e+09
1997,216.0,2.711944e+07,1.113595e+08,9277.0,542129.00,4809453.5,15487152.00,1.230075e+09
1998,217.0,2.737018e+07,1.125789e+08,9306.0,550430.00,4869626.0,15707209.00,1.241935e+09
1999,217.0,2.774105e+07,1.139891e+08,9345.0,569447.00,4949660.0,16016092.00,1.252735e+09
2000,217.0,2.810829e+07,1.153542e+08,9420.0,592267.00,5026796.0,16440924.00,1.262645e+09
2001,217.0,2.847465e+07,1.166814e+08,9512.0,607389.00,5111770.0,16983266.00,1.271850e+09
2002,217.0,2.883902e+07,1.179739e+08,9635.0,609828.00,5200598.0,17366517.00,1.280400e+09
2003,217.0,2.920432e+07,1.192368e+08,9767.0,623434.00,5240879.0,17679355.00,1.288400e+09
2004,217.0,2.957225e+07,1.204839e+08,9894.0,640282.00,5372280.0,17997738.00,1.296075e+09
2005,217.0,2.994271e+07,1.217276e+08,10027.0,656639.00,5379328.0,18336724.00,1.303720e+09
2006,217.0,3.031637e+07,1.229544e+08,10071.0,672228.00,5437272.0,18914977.00,1.311020e+09
2007,217.0,3.069266e+07,1.241581e+08,10002.0,686958.00,5522106.0,19632806.00,1.317885e+09
2008,217.0,3.107511e+07,1.253514e+08,9947.0,700950.00,5594506.0,19996469.00,1.324655e+09
2009,217.0,3.145848e+07,1.265246e+08,9945.0,714458.00,5666581.0,20367487.00,1.331260e+09
2010,217.0,3.184208e+07,1.276772e+08,10025.0,727641.00,5737723.0,20401331.00,1.337705e+09
2011,217.0,3.222029e+07,1.288089e+08,10057.0,740510.00,5807820.0,20863993.00,1.344130e+09
2012,216.0,3.273951e+07,1.302253e+08,10279.0,745692.25,6037683.0,21166438.00,1.350695e+09
2013,216.0,3.313492e+07,1.313513e+08,10819.0,753935.75,6070858.5,21733364.25,1.357380e+09
2014,216.0,3.353326e+07,1.324826e+08,10908.0,762391.00,6109052.5,22312765.50,1.364270e+09
2015,216.0,3.393172e+07,1.336143e+08,11001.0,775196.50,6158495.0,22903009.50,1.371220e+09
2016,216.0,3.433192e+07,1.347661e+08,11097.0,790026.50,6221590.5,23503371.50,1.378665e+09
2017,216.0,3.473027e+07,1.359261e+08,11192.0,800172.25,6296098.5,24113982.75,1.386395e+09

### Challenge 1: Population Growth

In [167]:
def get_population_growth_rate_by_country_year(df, country_code):
    country_series = df.loc[country_code]
    
    # create an empty list to store the results
    results = []
    
    for i in range(1, len(country_series)):
        prev_pop = country_series.iloc[i - 1]
        curr_pop = country_series.iloc[i]
        
        year = country_series.index[i]
        
        growth_rate = (curr_pop - prev_pop) / prev_pop
        
        results.append([
            float(year),
            round(growth_rate, 5)
        ])
    
    return np.array(results)

In [168]:
get_population_growth_rate_by_country_year(population_df, 'ABW')

array([[ 1.961e+03,  2.263e-02],
       [ 1.962e+03,  1.420e-02],
       [ 1.963e+03,  8.360e-03],
       [ 1.964e+03,  5.940e-03],
       [ 1.965e+03,  5.750e-03],
       [ 1.966e+03,  6.190e-03],
       [ 1.967e+03,  5.890e-03],
       [ 1.968e+03,  5.700e-03],
       [ 1.969e+03,  5.820e-03],
       [ 1.970e+03,  5.740e-03],
       [ 1.971e+03,  6.380e-03],
       [ 1.972e+03,  6.730e-03],
       [ 1.973e+03,  6.730e-03],
       [ 1.974e+03,  4.730e-03],
       [ 1.975e+03,  2.130e-03],
       [ 1.976e+03, -1.170e-03],
       [ 1.977e+03, -3.630e-03],
       [ 1.978e+03, -4.360e-03],
       [ 1.979e+03, -2.050e-03],
       [ 1.980e+03,  1.930e-03],
       [ 1.981e+03,  7.840e-03],
       [ 1.982e+03,  1.285e-02],
       [ 1.983e+03,  1.395e-02],
       [ 1.984e+03,  1.021e-02],
       [ 1.985e+03,  3.020e-03],
       [ 1.986e+03, -6.060e-03],
       [ 1.987e+03, -1.295e-02],
       [ 1.988e+03, -1.219e-02],
       [ 1.989e+03, -7.700e-04],
       [ 1.990e+03,  1.830e-02],
       [ 1.991e+03,  3.979e-02],
       [ 1.992e+03,  5.591e-02],
       [ 1.993e+03,  6.256e-02],
       [ 1.994e+03,  5.787e-02],
       [ 1.995e+03,  4.725e-02],
       [ 1.996e+03,  3.580e-02],
       [ 1.997e+03,  2.706e-02],
       [ 1.998e+03,  2.137e-02],
       [ 1.999e+03,  1.980e-02],
       [ 2.000e+03,  2.076e-02],
       [ 2.001e+03,  2.251e-02],
       [ 2.002e+03,  2.254e-02],
       [ 2.003e+03,  2.132e-02],
       [ 2.004e+03,  1.773e-02],
       [ 2.005e+03,  1.311e-02],
       [ 2.006e+03,  8.010e-03],
       [ 2.007e+03,  3.850e-03],
       [ 2.008e+03,  1.310e-03],
       [ 2.009e+03,  9.900e-04],
       [ 2.010e+03,  2.130e-03],
       [ 2.011e+03,  3.780e-03],
       [ 2.012e+03,  5.130e-03],
       [ 2.013e+03,  5.950e-03],
       [ 2.014e+03,  5.890e-03],
       [ 2.015e+03,  5.260e-03],
       [ 2.016e+03,  4.610e-03],
       [ 2.017e+03,  4.220e-03]])

### Challenge 2: Even-odd train-test split

In [171]:
def feature_response_split(arr):
    X = arr[:, 0]
    y = arr[:, 1]
    
    # split masks
    even_mask = X % 2 == 0
    
    X_train = X[even_mask]
    X_test = X[~even_mask]
    y_train = y[even_mask]
    y_test = y[~even_mask]
    
    return (X_train, y_train), (X_test, y_test)

In [172]:
data = get_population_growth_rate_by_country_year(population_df, 'ABW')
(X_train, y_train), (X_test, y_test) = feature_response_split(data)

In [166]:
y_train

array([ 0.0142 ,  0.00594,  0.00619,  0.0057 ,  0.00574,  0.00673,
        0.00473, -0.00117, -0.00436,  0.00193,  0.01285,  0.01021,
       -0.00606, -0.01219,  0.0183 ,  0.05591,  0.05787,  0.0358 ,
        0.02137,  0.02076,  0.02254,  0.01773,  0.00801,  0.00131,
        0.00213,  0.00513,  0.00589,  0.00461])

### Challenge 3: Fitting a Model using sklearn's `DecisionTreeRegressor`

In [119]:
X_train = X_train.reshape(-1,1)
X_test = X_test.reshape(-1,1)

In [164]:
def train_model(X_train, y_train, MaxDepth):
    X_train = X_train.reshape(-1,1)
    
    tree = DecisionTreeRegressor(max_depth=MaxDepth, random_state=42)
    tree.fit(X_train, y_train)
    
    return tree

In [113]:
data = get_population_growth_rate_by_country_year(population_df, 'ABW')
(X_train, y_train), _ = feature_response_split(data)

train_model(X_train, y_train, 3).predict([[2017]])

array([0.00451333])

### Challenge 4: Now we would like to test our model on the testing data that we produced in Exercise 2. This test will give the Root Mean Squared Logarithmic Error (RMSLE)

In [165]:
from sklearn.metrics import mean_squared_log_error

In [159]:
def test_model(model, y_test, X_test):
    X_test = X_test.reshape(-1, 1)
    y_pred = model.predict(X_test)
    
    y_pred = np.clip(y_pred, 0, None)
    y_test = np.clip(y_test, 0, None)
    
    rmsle = np.sqrt(mean_squared_log_error(y_test, y_pred))
    
    return float(round(rmsle, 3))

In [160]:
data = get_population_growth_rate_by_country_year(population_df, 'ABW')
(X_train, y_train), (X_test, y_test) = feature_response_split(data)

lm = train_model(X_train, y_train, 3)
test_model(lm, y_test, X_test)

0.007